# Generated by Django 4.0.1 on 2022-02-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_orders_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('update_desc', models.CharField(choices=[('Stg1', 'Order has been placed.'), ('Stg2', 'Order packed and out for delivery.'), ('Stg3', 'Order Delivered!')], default='Stg1', max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
